local op = vim.opt                   -- variable local
op.acd = true                        -- change directory to the file in the current window
op.ai = true                         -- take indent for new line from previous line
op.ar = true                         -- autom. read file when changed outside of Vim
op.bg = "dark"                       -- "dark" or "light", used for highlight colors
op.bs = { "start", "eol", "indent" } -- how backspace works at start of line
op.bk = false                        -- keep backup file after overwriting a file
op.cb:append("unnamedplus")          -- uses system clipboard
op.ch = 2                            -- number of lines to use for the command-line
op.cf = true                         -- ask what to do about unsaved/read-only files
op.ci = true                         -- make 'autoindent' use existing indent structure
op.cul = true                        -- highlight the screen line of the cursor
op.culopt = "both"                   -- highlight line and number
op.et = true                         -- use spaces when <Tab> is inserted
op.gcr = ""                          -- cursor shape block always
op.ic = true                         -- ignore case in search patterns
op.is = true                         -- highlight match while typing search pattern
op.mouse = "nv"                      -- enable the use of mouse clicks in normal mode and visual
op.nu = true                         -- print the line number in front of each line
op.rdt = 500                         -- timeout for 'hlsearch' and :match highlighting (milliseconds)
op.rnu = true                        -- show relative line number in front of each line
op.so = 8                            -- minimum nr. of lines above and below cursor
op.sw = 2                            -- number of spaces to use for (auto)indent step
op.sm = true                         -- briefly jump to matching bracket if insert one
op.siso = 10                         -- min. nr. of columns to left and right of cursor
op.scl = "yes"                       -- when and how to display the sign column
op.scs = true                        -- no ignore case when pattern has uppercase
op.sta = true                        -- <Tab> in leading whitespace indents by 'shiftwidth'
op.sb = true                         -- new window from split is below the current one
op.spr = true                        -- new window is put right of the current one
op.swf = false                       -- disable swapfile
op.ts = 2                            -- number of columns between two tab stops
op.tgc = true                        -- enable 24-bit RGB color in the TUI
op.udf = true                        -- save undo information in a file
op.wrap = false                      -- long lines wrap and continue on the next line
op.sts = 2                           -- number of columns between two soft tab stops
op.si = true                         -- smart autoindenting for C programs
op.ut = 50                           -- after this many milliseconds flush swap file
op.hls = true                        -- highlight matches with last search pattern
-- op.colorcolumn = 80 -- columns to highlight
-- op.ea = true -- windows are automatically made the same size
